name: Docker Image CI for almalinux8 (dev)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create the secret
      working-directory: ./dev/
      run: |
        touch secret.yml
        echo 'credential:' > secret.yml
        echo '   endpoint: https://discord.com/api/webhooks/1090840367097729054/0HZJN7s0FY0xNxVnJ1HGGRZua9ChFQkU1WoV-SbKcqAvkjWs1yFoXF83bs90zF7AAa69?wait=true' >> secret.yml

    - name: Build the Docker image
      working-directory: ./dev/
      run: |
        set -x && docker build . --file Dockerfile --tag n138-kz/oshiire-bot:latest --tag n138-kz/oshiire-bot:$(date +%s)

    - name: Test RUN the Docker image
      working-directory: ./dev/
      run: |
        set -x && docker run --rm n138-kz/oshiire-bot
