name: Docker Image CI for almalinux8 (prd)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  send_github_context:
    uses: n138-kz/n138-kz/.github/workflows/github-act_send_github_context.yml@main
    # https://github.com/n138-kz/n138-kz/blob/main/.github/workflows/github-act_send_github_context.yml
    secrets: inherit # pass all secrets

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create the secret
      working-directory: ./prd/
      run: |
        touch secret.yml
        echo 'credential:' > secret.yml
        echo '   endpoint: ' >> secret.yml
        echo 'https://discord.com/api/webhooks/00000/fFfFfFfFfF' >> secret.yml
        echo '?wait=true' >> secret.yml

    - name: Build the Docker image
      working-directory: ./prd/
      run: |
        set -x && docker build . --file Dockerfile --tag n138-kz/oshiire-bot:latest --tag n138-kz/oshiire-bot:$(date +%s)

    - name: Build the Docker image
      working-directory: ./prd/
      run: |
        set -x && docker build . --file Dockerfile --tag n138-kz/oshiire-bot:latest --tag n138-kz/oshiire-bot:prd
