name: Docker Image CI for almalinux8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: set -x && touch secret.yml && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./latest/
